export const NGO_CAUSE_OPTIONS = [
  'Climate & Environment',
  'Education',
  'Health',
  'Human Rights',
  'Youth Empowerment',
  'Poverty Alleviation',
  'Gender Equality',
  'Refugee & Migration',
  'Animal Welfare',
  'Arts & Culture',
  'Digital Inclusion',
  'Community Development',
  'Mental Health',
  'Disaster Relief',
  'Food Security',
] as const;

export const NGO_NEED_OPTIONS = [
  'Volunteers',
  'Graphic Design',
  'Web Development',
  'Content Writing',
  'Event Coordination',
  'Fundraising',
  'Legal Support',
  'Marketing & Communications',
  'Translation',
  'Project Management',
  'Research',
  'Mentoring',
  'Logistics',
  'Photography & Video',
  'Social Media Management',
] as const;
